version: '3.8'

services:
  data-collection-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - HOST=0.0.0.0
      - PORT=8002
      - DEBUG=true
      - REDIS_URL=redis://redis:6379/0
      - USE_VECTOR_DB=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./vector_db:/app/vector_db
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - data-collection-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - data-collection-network
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  data-collection-network:
    driver: bridge 