auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Configure retention
limits_config:
  retention_period: 744h # 31 days retention
  max_query_series: 100000
  max_query_parallelism: 32
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 8MB
  per_stream_rate_limit_burst: 16MB

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 744h

# Analytics and usage stats (disabled for demo)
analytics:
  reporting_enabled: false
